const mutations = {
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  LOGIN_LOADER: 'LOGIN_LOADER',
  SHOW_NOTIFY: 'SHOW_NOTIFY',
  USER: 'USER',
  IS_FIRST_LOGIN: 'IS_FIRST_LOGIN',
  PUBLIC_CHATS: 'PUBLIC_CHATS',
  SELECT_CHAT_ID: 'SELECT_CHAT_ID',
  CURRENT_CHAT: 'CURRENT_CHAT',
  CURRENT_CHAT_MSGS: 'CURRENT_CHAT_MSGS',
  NEW_MSG: 'NEW_MSG'
};

export default mutations;
